apiVersion: apps/v1
kind: Deployment
metadata:
  name: launchpad-lite-demo
  labels:
    app.kubernetes.io/name: launchpad-lite-demo
    app.kubernetes.io/part-of: launchpad-lite
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: launchpad-lite-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: launchpad-lite-demo
    spec:
      containers:
        - name: launchpad-lite-demo
          image: docker.io/chrisvon7/launchpad-lite-demo:dev
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
