apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: docker.io/artcrafter/tekton-hello
    newTag: v0.1.0-20260505175830
commonLabels:
  app.kubernetes.io/managed-by: launchpad-lite
